### PR TITLE
[WIP] Fix/mtMemLeak removes memory leak from multithreaded routines

### PR DESCRIPTION
**Pull request by hkashyap**
- [x] Remove memory leak for pthread_attributes
- [ ] Remove memory leak in SNN::copyAuxiliaryData

### CODE REVIEW

**Comment by hkashyap** [comment]
We still have some leak here:

4,096 bytes in 1 blocks are definitely lost in loss record 1 of 2
==15777==    at 0x4C2B8A8: operator new[](unsigned long) (vg_replace_malloc.c:423)
==15777==    by 0x465F92: SNN::copyAuxiliaryData(int, int, RuntimeData_s*, bool) (in /home/hirak/CARLsim4/projects/hello_world/hello_world)
==15777==    by 0x467FB4: SNN::allocateSNN_CPU(int) (in /home/hirak/CARLsim4/projects/hello_world/hello_world)
==15777==    by 0x43CD48: SNN::generateRuntimeSNN() (in /home/hirak/CARLsim4/projects/hello_world/hello_world)
==15777==    by 0x406431: CARLsim::setupNetwork() (in /home/hirak/CARLsim4/projects/hello_world/hello_world)
==15777==    by 0x405281: main (in /home/hirak/CARLsim4/projects/hello_world/hello_world)

**Comment by mbeyeler** [comment]
Sorry, I thought we're waiting on the other to-do item to be done. It's great to have memory leaks fixed and the tests pass again!

**Comment by hkashyap** [comment]
We were not sure about at what point we should delete the aux data. It was a leak of some 8KB. Did not seem to be a major problem and I guess that's why Ting merged.

**Comment by tingshuc** [comment]
It is intriguing. I don't think I merge fix/mtMemLeak into master. Does this happen automatically because feat/testNoCuda included fix/mtMemLeak and was merged into master?!

**Comment by hkashyap** [comment]
memory leak in SNN::copyAuxiliaryData() is fixed with PR https://github.com/UCI-CARL/CARLsim4/pull/27

**Pull request merged**
